baseURL: https://brcha.com/
languageCode: en-us
title: "Brcha's website"
theme: "PaperMod"

params:
  title: "Brcha's website"
  description: ""
  author: "Filip Brcic"

  googleAnalytics: "UA-1576212-8"

  profileMode:
    enabled: true
    title: "Brcha's website"
    subtitle: "Control systems engineer & developer"
    imageUrl: "images/logoF-new-t.png"

  socialIcons:
    - name: email
      url: "https://mailhide.io/e/A3sZPT2n"
    - name: github
      url: "https://github.com/brcha"
    - name: gitlab
      url: "https://gitlab.com/brcha"
    - name: linkedin
      url: "https://www.linkedin.com/in/filip-br%C4%8Di%C4%87-2b19431a6/"

